language: java
jdk: openjdk8

# This comes from the docs at
# https://docs.travis-ci.com/user/languages/java/#caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - openssl aes-256-cbc -K $encrypted_2608174d164b_key -iv $encrypted_2608174d164b_iv -in .travis/secret.gpg.enc -out .travis/secret.gpg -d
  - gpg --import .travis/secret.gpg

install:
  # JSoar needs to be on the classpath in order for the shadow tasks
  # to successfully be configured - it's not enough to simply declare
  # it as a task dependency.
  - ./gradlew compileJSoar
  - (cd integrations/vscode && npm install)

script:
  - ./gradlew check
  - (cd integrations/vscode && npm run compile)

before_deploy:
  - ./gradlew assemble
  - ./gradlew shadowDistTar shadowDistZip installShadowDist
deploy:
# Publish the plugin to GitHub releases.
#
# The API key is associated with an individual's GitHub account.
# Create it here: https://github.com/settings/tokens
- provider: releases
  api_key:
    secure: cO2gM42kllxCrIvuSpf5pGSAg1kzUUAQ5hm/0pXXTLj384vRnLnVysXXJdM1G2DYwQifcIZDFTjyBozeaIUt5AT5JJreSJJX7o+FtlEPh/OWYjqyNAFm6gbF0ANM2XNQQwaDe0rP5vB9uUsVgGUAuxmJ6ntc3TU+HnX6wA8Hc0CEH5ft+ncym5LuXaiUVm0tW5wGoEIhxsuc96xcWdyRk7r6G6BwZiYcvKhnC2BbK7EzUAm931IkWqK739awrnfDlTjqVK4f01K5bvZhfZK4vQjjkKd1BIQztBnQ+ejCn9/FIFk980RC7JIRRjy4Xbg06vi+q5cOZuxrmOWSupHqBfYs14V8M7tUfdIRBYDIn9dRnTGPHXDkqzAR1uXVVl8nrXIyZznlj5iHZh1UoDAHpFS8lSdKnvtbhwh0Sx8pxu5lhIuGUzoQj9goqYku8oHoKUFv+aiFOFrUvEIHoWqnGvxcQoovdH1btV3qXRoMZSyksz3sDQwWyBYuTJpTlu3NAQf4OqeUoRTKRLQd5FTbaaW694z9Xi2kiAURzpJfIGZZaxfJEM8PA8pIoA5K7ZOZm6127gWVWolhHlWLmwAaOVn4MU9QDqknLav7EYx3VCWO65DUW3Jym/BFlj7BVgW4VfKAlLc5NtIf3ND6oIxCaV6qKSUrSwC2DgP5MiIDwEM=
  file_glob: true
  file:
    - build/distributions/*
    - integrations/vscode/soar-language-support-*.vsix
  skip_cleanup: true
  on:
    tags: true
    repo: soartech/soar-language-server
# Publish the plugin to the VSCode marketplace.
#
# The VSCE_TOKEN is associated with an account created on dev.azure.com
# It can be generated by following the instructions here:
# https://code.visualstudio.com/api/working-with-extensions/publishing-extension
- provider: script
  script: (cd integrations/vscode && npx vsce publish -p $VSCE_TOKEN)
  skip_cleanup: true
  on:
    tags: true
    repo: soartech/soar-language-server
# Publish the library to Maven Central.
#
# This usually fails because there are bugs related to Travis in the nexus-staging Gradle plugin.
# Because of this, we run this releas *last*, so that the other steps succeed even if/when this fails.
# See here for more details on this bug:
# https://github.com/Codearte/gradle-nexus-staging-plugin/#2-why-my-release-build-on-travis-suddenly-started-to-fail-with-wrong-number-of-received-repositories
- provider: script
  script: ./gradlew uploadArchives && ./gradlew closeAndReleaseRepository
  skip_cleanup: true
  on:
    tags: true
    repo: soartech/soar-language-server
