language: java

# This comes from the docs at
# https://docs.travis-ci.com/user/languages/java/#caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  # JSoar needs to be on the classpath in order for the shadow tasks
  # to successfully be configured - it's not enough to simply declare
  # it as a task dependency.
  - ./gradlew compileJSoar
  - ./gradlew verifyGoogleJavaFormat
  - ./gradlew assemble

before_deploy:
  - ./gradlew shadowDistTar shadowDistZip
deploy:
- provider: releases
  api_key:
    secure: cO2gM42kllxCrIvuSpf5pGSAg1kzUUAQ5hm/0pXXTLj384vRnLnVysXXJdM1G2DYwQifcIZDFTjyBozeaIUt5AT5JJreSJJX7o+FtlEPh/OWYjqyNAFm6gbF0ANM2XNQQwaDe0rP5vB9uUsVgGUAuxmJ6ntc3TU+HnX6wA8Hc0CEH5ft+ncym5LuXaiUVm0tW5wGoEIhxsuc96xcWdyRk7r6G6BwZiYcvKhnC2BbK7EzUAm931IkWqK739awrnfDlTjqVK4f01K5bvZhfZK4vQjjkKd1BIQztBnQ+ejCn9/FIFk980RC7JIRRjy4Xbg06vi+q5cOZuxrmOWSupHqBfYs14V8M7tUfdIRBYDIn9dRnTGPHXDkqzAR1uXVVl8nrXIyZznlj5iHZh1UoDAHpFS8lSdKnvtbhwh0Sx8pxu5lhIuGUzoQj9goqYku8oHoKUFv+aiFOFrUvEIHoWqnGvxcQoovdH1btV3qXRoMZSyksz3sDQwWyBYuTJpTlu3NAQf4OqeUoRTKRLQd5FTbaaW694z9Xi2kiAURzpJfIGZZaxfJEM8PA8pIoA5K7ZOZm6127gWVWolhHlWLmwAaOVn4MU9QDqknLav7EYx3VCWO65DUW3Jym/BFlj7BVgW4VfKAlLc5NtIf3ND6oIxCaV6qKSUrSwC2DgP5MiIDwEM=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    tags: true
    repo: soartech/soar-language-server
- provider: script
  script: ./gradlew publish
  on:
    repo: soartech/soar-language-server
    branch: master

env:
  global:
  # NEXUS_USERNAME
  -  secure: "bOq11I5vbuqPU+ivqVcGYazUjgET5rhx+VzzdcrdbmOGA46WqgkfcI8hzWEUEUqc9r6THWR8Enea03q3o+3zaVLHpDWfSR6p8R0l61VM/IR6UY1Dh3LGG3uqH7GNjVU7gT9RurVLvHy/k+MzhUAcSDrMG3rNolrCOPQFoh6qKd2n3plQMSbl9ZoqfbP7dFbVv+nGnzfwvkRkcMoTf3fD9bjk/DYr/0q/FsrMmog+B7u5PgYXJdVepbiMRy6/j3J9qVbpm3Z7tn2q2yeWce7wc9D9d5E8FEFgACFTCGURq0G9ZzI844asz82YmkjsIhdevWISGKIcxXIobZGJMlVwHlXBUrlZ1ETmmW8HG2zA1E1wvUipzOaOlADRpa0a7GriuN8MFp+KguTAbrEYJgGtnla6HrisIgt8Dz572RViRYkvyjqW2eM4p5xD1X54BqE94RtTGjoPRVagDGqfoSS12nDlEFU6s6Bv6Zbk4AV4i9FTGilu5mukNnLhekE/QzFierq0RXjhKaDf6J+wXZ5Mnz0GFhC+VkVXB98l5PASDTfyPNa8+s+q57bJ7/3C5Mrp7V2Ny7V432YUENs6pT4/jBdRP612d10wkYzd1TB4AnAlnmc+S/9yGPVk18fDqlJF7IYhIbfZmQ0E0Ce6pL0LK0pQaf6QzWwMEtAro6cV8V8="

  # NEXUS_PASSWORD
  - secure: G8OS7LAsl+qrsuxhjcKIjDXbe/Hu79KPKdv8AgN1xqaRSHZqJC50m0+TOS8TIx4E2x3ydZcwaz16p5UB8epcPQtD6JVJL2FenKeLCIX4a5PGUhDk25/WBmgBGE0ON3FlSr74fV7SNeEdoRwpLHwTVDr+/bvupiVbltuGy7poBKVfe7ng47CoKCgaL8J9vvLZaJLl4yLIP2VvApVKJ6SqTjv9Mty0Sh+2y9Vq1Q0gLkgF7biJ87GrpwFwUrma5kxXIyzUIBReSUNgahfPuxHCYAvdry0Tuvbc7ELkVslNL4q6hPMiDYISWqOGH5JWP+Ly/Y6vESS6+Ibe5npwXYDjz3/QOJ42TgSj0EtxTqJRBHFxesJK9dSOarZL3OUi8LKNt8sobPZ6dh4Pb2JWfk5Sz6zfH4nQilomi3m1xDql1Gv6S3m6sS04wxO0uQxVgPVPB02/WqLbvXLXPG7zMUod0IOGTt8DTpwgHl9y6mcs62fwsUiMjNgpztd1jVsybIgst3KxNlvZYTjfAA3/HQ9A2kReJbbb7IJn19a2BKOhvfDnxIkJKi9FFLtDhMTy4JCNUaMEF1AxbCzcJmnedCqnk6e8IdlBfm0hy8TuEQrnQSgKekOAFxe5iYwxhudIQ0qMRV7O2XuLmnd803YJXpP35JnWVtmP+hKrQjsRJnI82nk=
