version: "{branch} {build}"

install:
  - git submodule -q update --init
  - gradlew.bat compileJSoar
  - (cd integrations/vscode && npm install)

build_script:
  - gradlew.bat classes

test_script:
  - gradlew.bat check
  - (cd integrations/vscode && npm test)

cache:
  - C:\Users\appveyor\.gradle
  - C:\Users\appveyor\build
