version: "{branch} {build}"

install:
  - git submodule -q update --init
  - gradlew.bat compileJSoar

build_script:
  - gradlew.bat assemble

test_script:
  - gradlew.bat check

cache:
  - C:\Users\appveyor\.gradle
  - C:\Users\appveyor\build
