version: "{branch} {build}"

install:
  - cmd: git submodule -q update --init

build_script:
  - gradlew.bat assemble

test_script:
  - gradlew.bat check

cache:
  - C:\Users\appveyor\.gradle
  - C:\Users\appveyor\build
